name: Run linting

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.14
      - name: Install dependencies
        run: go get .
      - name: Test
        run: go test -v ./...